name: 'dbt_tableau_wrangler'
version: '0.2.0'
config-version: 2


models:
  dbt_tableau_wrangler:
    +schema: default_dbt_tableau_wrangler_schema
    +materialized: table
    incremental:
      +materialized: incremental
    staging:
      +materialized: view # The staging tables cannot be ephemeral
